const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
const esc = v => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const now = () => new Date().toISOString();
const DB_KEY = "ecometrica_pwa_v1";
const SUPABASE_URL = "https://rwwuughzhbhdjjouwvpu.supabase.co";
const SUPABASE_KEY = "sb_publishable_U6RAEtAHX1ypzRmNXgY2gA_aBRVRphy";
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
let authReady = false;

const defaultState = {
  user:null,
  users:[],
  sessions:[], articles:[], screeningSessions:[], screeningDecisions:[], eligibilityDecisions:[], activities:[], occurrences:[]
};
let state = load();
function load(){try{return {...structuredClone(defaultState),...JSON.parse(localStorage.getItem(DB_KEY)||"{}"),user:null,users:[]} }catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(DB_KEY,JSON.stringify({...state,user:null,users:[]}))}
function toast(msg){const e=$("#toast");e.textContent=msg;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2400)}
function activity(type,description,sessionName=""){state.activities.unshift({id:uid(),type,description,sessionName,createdAt:now(),owner:state.user?.id});save()}
function mine(list){return state.user?.role==="admin"?list:list.filter(x=>x.owner===state.user?.id)}
function download(name,text,type="text/plain"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function route(){return location.hash.replace(/^#\/?/,"")|| (state.user?"dashboard":"home")}
function go(path){location.hash=`#/${path}`}

const nav=[
  ["dashboard","Dashboard","▦"],["search","Construtor de Busca","⌕"],["map","Mapa de Espécies","⌖"],["corpus","Corpus","⇧"],
  ["sessions","Sessões de Análise","◫"],["screening","Triagem de Artigos","✓"],["eligibility","Elegibilidade","◎"],
  ["prisma","Diagrama PRISMA","↳"],["results","Resultados","▥"],["vosviewer","VOSviewer","⌘"],["admin","Administração","⚙"]
];

function appFooter(){return `<footer class="footer"><img class="footer-logo" src="icons/decb-uern.png" alt="Logomarca do Departamento de Ciências Biológicas da UERN"><div>Universidade do Estado do Rio Grande do Norte — UERN © 2026</div><div>Desenvolvido pelo Prof. Egberto Mesquita com a ferramenta de IA ChatGPT</div></footer>`}
function landing(){return `<div class="landing"><header class="public-nav"><div class="brand"><img src="icons/icon.svg" alt=""><span>EcoMétrica</span></div><div class="actions"><button class="btn btn-outline" data-go="login">Entrar</button><button class="btn btn-primary" data-go="register">Criar conta</button></div></header><main><section class="hero"><span class="eyebrow">PPGCN · UERN</span><h1>Plataforma Cienciométrica para Espécies Invasoras</h1><p>Ferramenta de revisão bibliográfica sistemática sobre espécies animais exóticas invasoras em ambientes aquáticos continentais da Caatinga, com foco no Rio Grande do Norte.</p><div class="actions"><button class="btn btn-primary" data-go="register">Começar revisão</button><button class="btn btn-outline" data-go="login">Já tenho acesso</button></div></section><section class="features">${[["Triagem Sistemática","Avalie títulos e resumos com critérios transparentes."],["Diagrama PRISMA","Acompanhe cada etapa da seleção de estudos."],["Análise Cienciométrica","Explore tendências, autores, periódicos e descritores."],["Mapa de Ocorrências","Consulte registros públicos de espécies via GBIF."]].map(x=>`<article class="feature"><span class="eyebrow">${x[0]}</span><b>${x[0]}</b><p>${x[1]}</p></article>`).join("")}</section></main>${appFooter()}</div>`}
function authPage(kind){const reg=kind==="register";return `<div class="auth-wrap"><form class="card auth-card" id="auth-form"><div class="brand"><img src="icons/icon.svg" alt=""><span>EcoMétrica</span></div><h1>${reg?"Criar conta":"Bem-vindo de volta"}</h1><p class="muted">${reg?"Cadastre-se para iniciar sua revisão.":"Entre com sua conta segura."}</p><button type="button" class="btn btn-google" id="google-login"><span class="google-mark" aria-hidden="true">G</span>Continuar com Google</button><div class="auth-divider"><span>ou use seu e-mail</span></div>${reg?`<div class="field"><label>Nome</label><input name="name" required autocomplete="name"></div>`:""}<div class="field"><label>E-mail</label><input name="email" type="email" required autocomplete="email"></div><div class="field"><label>Senha</label><input name="password" type="password" minlength="8" required autocomplete="${reg?"new-password":"current-password"}"></div>${reg?`<div class="field"><label>Instituição</label><input name="institution" value="PPGCN/UERN" autocomplete="organization"></div>`:""}<button type="submit" class="btn btn-primary" style="width:100%">${reg?"Criar conta":"Entrar"}</button><p class="auth-switch">${reg?`Já possui uma conta? <a href="#/login">Entrar</a>`:`Ainda não possui uma conta? <a href="#/register">Criar conta</a>`}</p><button type="button" class="btn btn-outline" style="width:100%;margin-top:8px" data-go="home">Voltar</button></form></div>`}

function shell(content){const r=route();return `<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><img src="icons/icon.svg" alt=""><span>EcoMétrica</span></div><nav>${nav.filter(x=>x[0]!=="admin"||state.user.role==="admin").map(([p,l,i])=>`<a href="#/${p}" class="nav-link ${r.startsWith(p)?"active":""}"><span>${i}</span> ${l}</a>`).join("")}</nav><div class="sidebar-foot">PPGCN/UERN<br>Dados armazenados neste dispositivo</div></aside><section class="app-main"><header class="topbar"><button class="menu-toggle" id="menu-toggle" aria-label="Abrir menu">☰</button><div class="muted">Revisão sistemática · RN · 2004–2025</div><div class="user-chip"><span class="avatar">${esc(state.user.name.slice(0,2).toUpperCase())}</span><span class="user-text"><b>${esc(state.user.name)}</b><br><small>${state.user.role==="admin"?"Administrador":"Pesquisador"}</small></span><button class="btn btn-outline btn-sm" id="logout">Sair</button></div></header><main class="content">${content}</main>${appFooter()}</section></div>`}
function head(title,desc,actions=""){return `<header class="page-head"><div class="toolbar" style="justify-content:space-between"><div><h1>${title}</h1><p>${desc}</p></div>${actions}</div></header>`}
function empty(title,text,button=""){return `<div class="card empty"><h2>${title}</h2><p class="muted">${text}</p>${button}</div>`}

function dashboard(){const sessions=mine(state.sessions), articles=mine(state.articles), decisions=mine(state.screeningDecisions), occ=mine(state.occurrences);const screened=decisions.filter(x=>x.decision!=="pending").length,total=decisions.length,progress=total?Math.round(screened/total*100):0;return `${head("Dashboard","Visão geral da revisão sistemática sobre espécies exóticas invasoras na Caatinga.")}<section class="grid metrics"><article class="card metric"><small>Sessões de análise</small><div class="value">${sessions.length}</div></article><article class="card metric"><small>Artigos no corpus</small><div class="value">${articles.filter(x=>!x.isDuplicate).length}</div></article><article class="card metric"><small>Artigos triados</small><div class="value">${screened}</div></article><article class="card metric"><small>Ocorrências GBIF</small><div class="value">${occ.length}</div></article></section><section class="grid two-col" style="margin-top:16px"><article class="card"><h2>Progresso da triagem</h2><div class="progress"><span style="width:${progress}%"></span></div><p><b>${progress}%</b> · ${screened} de ${total||0} registros avaliados</p>${sessions.length?`<button class="btn btn-primary" data-go="sessions">Ver sessões</button>`:`<div class="notice">Crie sua primeira sessão importando um corpus bibliográfico.</div><button class="btn btn-primary" data-go="corpus" style="margin-top:12px">Importar corpus</button>`}</article><article class="card"><h2>Atividades recentes</h2>${mine(state.activities).slice(0,6).map(a=>`<p><b>${esc(a.description)}</b><br><small class="muted">${new Date(a.createdAt).toLocaleString("pt-BR")}</small></p>`).join("")||`<p class="muted">Nenhuma atividade registrada.</p>`}</article></section>`}

const databases={wos:["Web of Science","https://www.webofscience.com","TS=({Q}) AND PY=({Y1}-${Y2})"],scopus:["Scopus","https://www.scopus.com","TITLE-ABS-KEY({Q}) AND PUBYEAR > {YM1} AND PUBYEAR < {YP1}"],openalex:["OpenAlex","https://openalex.org","{Q}"],scielo:["SciELO","https://search.scielo.org","{Q}"],scholar:["Google Scholar","https://scholar.google.com","{Q}"],gbif:["GBIF","https://www.gbif.org","{Q}"],horus:["Base Hórus","https://institutohorus.org.br","{Q}"]};
const groups={
 invasive:["Espécies exóticas invasoras",["invasive species","invasive alien species","alien species","non-native species","introduced species","exotic species","biological invasion","espécie exótica invasora","espécie invasora","espécie não nativa","espécie introduzida","invasão biológica"]],
 fauna:["Fauna aquática",["fish*","ichthyofauna","mollusk*","mollusc*","crustacean*","amphibian*","reptile*","aquatic fauna","freshwater fauna","peixe*","ictiofauna","molusco*","crustáceo*","anfíbio*","réptil*","fauna aquática"]],
 ponds:["Açudes",["small reservoir*","semi-arid reservoir*","farm pond*","weir*","small dam*","açude*","pequeno reservatório*","reservatório do semiárido"]],
 dams:["Barragens",["dam*","large reservoir*","impoundment*","barragem*","grande reservatório*"]],
 aquatic:["Ambientes aquáticos",["freshwater ecosystem*","continental aquatic ecosystem*","lentic environment*","lotic environment*","temporary pond*","rivers","lakes","reservoirs","ecossistema de água doce","ambiente lêntico","ambiente lótico","lagoa temporária","rios","lagos","reservatórios"]],
 caatinga:["Caatinga",["Caatinga","semiarid","semi-arid","Brazilian semiarid","Northeastern Brazil","semiárido brasileiro","Nordeste brasileiro"]],
 rn:["Rio Grande do Norte",["Rio Grande do Norte","state of Rio Grande do Norte","estado do Rio Grande do Norte"]]
};
function quote(t){return /\s/.test(t)?`"${t}"`:t}
function buildQuery(selected,op){return selected.map(id=>`(${groups[id][1].map(quote).join(" OR ")})`).join(` ${op} `)}
function searchPage(){return `${head("Construtor de Busca","Monte estratégias booleanas adaptadas às principais bases científicas.")}<form id="search-form" class="grid two-col"><section class="card"><h2>1. Bases</h2><div class="check-grid">${Object.entries(databases).map(([id,d])=>`<label class="check"><input type="checkbox" name="db" value="${id}" ${["wos","scopus","openalex","scielo","scholar"].includes(id)?"checked":""}><span><b>${d[0]}</b><br><small class="muted">${["wos","scopus"].includes(id)?"Acesso institucional":"Acesso externo"}</small></span></label>`).join("")}</div><h2 style="margin-top:22px">2. Conceitos</h2><div class="check-grid">${Object.entries(groups).map(([id,g])=>`<label class="check"><input type="checkbox" name="group" value="${id}" checked><span><b>${g[0]}</b><br><small class="muted">${g[1].length} termos</small></span></label>`).join("")}</div></section><aside class="card"><h2>3. Configurações</h2><div class="field"><label>Operador entre conceitos</label><select name="operator"><option>AND</option><option>OR</option><option>NOT</option></select></div><div class="field"><label>Idioma dos termos</label><select name="language"><option value="both">Português e inglês</option><option value="pt">Português</option><option value="en">Inglês</option></select></div><div class="grid two-col"><div class="field"><label>Ano inicial</label><input name="y1" type="number" value="2004"></div><div class="field"><label>Ano final</label><input name="y2" type="number" value="2025"></div></div><div class="field"><label>Bioma</label><select><option>Caatinga</option><option>Amazônia</option><option>Cerrado</option><option>Mata Atlântica</option><option>Pantanal</option><option>Pampa</option></select></div><div class="field"><label>Estado</label><select><option>Rio Grande do Norte</option><option>Todos</option></select></div><button class="btn btn-primary" style="width:100%">Gerar estratégias</button></aside></form><section id="strategies" class="grid" style="margin-top:18px"></section>`}
function renderStrategies(form){const f=new FormData(form),dbs=f.getAll("db"),sel=f.getAll("group");if(!dbs.length||!sel.length){toast("Selecione ao menos uma base e um grupo.");return}let filtered=structuredClone(groups);const lang=f.get("language");if(lang!=="both")for(const k in filtered)filtered[k][1]=filtered[k][1].filter(t=>lang==="pt"?/[^\x00-\x7F]|\b(de|do|da|em|rio|peixe|fauna|ambiente|espécie|invasão|reservatório|açude|barragem)/i.test(t):!/[^\x00-\x7F]|\b(de|do|da|peixe|fauna aquática|espécie|invasão|açude|barragem)/i.test(t));const op=f.get("operator"),q=sel.map(id=>`(${filtered[id][1].map(quote).join(" OR ")})`).join(` ${op} `),y1=+f.get("y1"),y2=+f.get("y2");const cards=dbs.map(id=>{const [name,url,tpl]=databases[id],out=tpl.replace("{Q}",q).replace("{Y1}",y1).replace("{Y2}",y2).replace("{YM1}",y1-1).replace("{YP1}",y2+1);return `<article class="card"><div class="toolbar" style="justify-content:space-between"><h3>${name}</h3><span class="badge">${["wos","scopus"].includes(id)?"Institucional":"Externo"}</span></div><div class="strategy" contenteditable="true">${esc(out)}</div><div class="toolbar"><button class="btn btn-outline btn-sm copy-strategy" type="button">Copiar</button><a class="btn btn-outline btn-sm" href="${url}" target="_blank" rel="noopener">Abrir base</a></div></article>`}).join("");$("#strategies").innerHTML=`<div class="toolbar"><h2 style="margin-right:auto">Estratégias geradas</h2><button id="export-strategies" class="btn btn-primary">Exportar TXT</button></div>${cards}`;}

function normalizeDOI(v=""){return v.toLowerCase().replace(/^https?:\/\/(dx\.)?doi\.org\//,"").replace(/^doi:\s*/,"").trim()}
function norm(v=""){return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function parseCSV(text){const lines=text.split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const delim=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?";":",";const split=line=>{let a=[],cur="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++}else if(c==='"')q=!q;else if(c===delim&&!q){a.push(cur);cur=""}else cur+=c}a.push(cur);return a};const h=split(lines[0]).map(norm);return lines.slice(1).map(line=>{const v=split(line),get=(...names)=>{const i=h.findIndex(x=>names.includes(x));return i>=0?v[i]?.trim():""};return {title:get("title","titulo","ti"),abstract:get("abstract","resumo","ab"),authors:get("authors","autores","au"),journal:get("journal","periodico","jo","so"),year:+get("year","ano","py")||null,doi:get("doi","di"),keywords:get("keywords","palavras chave","kw"),citationCount:+get("citations","citacoes","tc")||0,source:get("source","fonte","db")||"CSV"}})}
function parseRIS(text){return text.split(/\nER\s*-\s*/).map(block=>{const f={};for(const line of block.split(/\r?\n/)){const m=line.match(/^([A-Z0-9]{2})\s*-\s*(.*)$/);if(m)(f[m[1]]??=[]).push(m[2])}return {title:(f.TI||f.T1||[])[0]||"",abstract:(f.AB||[])[0]||"",authors:(f.AU||[]).join("; "),journal:(f.JO||f.JF||f.T2||[])[0]||"",year:+String((f.PY||f.Y1||[])[0]||"").slice(0,4)||null,doi:(f.DO||[])[0]||"",keywords:(f.KW||[]).join("; "),citationCount:0,source:"RIS"}}).filter(x=>x.title)}
function parseBib(text){return [...text.matchAll(/@\w+\s*\{[^,]+,([\s\S]*?)(?=\n\}\s*(?:\n|$))/g)].map(m=>{const body=m[1],get=k=>{const r=body.match(new RegExp(`${k}\\s*=\\s*[\\{\"]([\\s\\S]*?)[\\}\"]\\s*,?`,`i`));return r?r[1].replace(/[{}]/g,"").trim():""};return {title:get("title"),abstract:get("abstract"),authors:get("author").replace(/\s+and\s+/gi,"; "),journal:get("journal"),year:+get("year")||null,doi:get("doi"),keywords:get("keywords"),citationCount:+get("cited-by")||0,source:"BibTeX"}}).filter(x=>x.title)}
function detectDuplicates(items){const groups=[];const seen=new Set;items.forEach((a,i)=>items.slice(i+1).forEach((b,jj)=>{const j=i+1+jj;const doi=normalizeDOI(a.doi)&&normalizeDOI(a.doi)===normalizeDOI(b.doi);const title=norm(a.title),same=title&&norm(b.title)===title&&(!a.year||!b.year||a.year===b.year);if((doi||same)&&!seen.has(j)){groups.push({a:i,b:j,reason:doi?"Mesmo DOI":"Título e ano equivalentes"});seen.add(j)}}));return groups}
let pendingImport=[];
function corpusPage(){return `${head("Corpus","Importe BibTeX, RIS ou CSV, revise os registros e crie uma sessão de análise.")}<section class="card"><div class="tabs"><span class="tab active">1 · Arquivos</span><span class="tab">2 · Prévia</span><span class="tab">3 · Deduplicação</span></div><div class="upload"><h2>Selecione um ou vários arquivos</h2><p class="muted">Formatos aceitos: .bib, .ris e .csv</p><input id="corpus-files" type="file" multiple accept=".bib,.ris,.csv,text/csv"></div><div id="corpus-preview"></div></section>`}
async function handleFiles(files){pendingImport=[];const warnings=[];for(const file of files){try{const text=await file.text(),ext=file.name.split(".").pop().toLowerCase();let rows=ext==="csv"?parseCSV(text):ext==="ris"?parseRIS(text):ext==="bib"?parseBib(text):[];rows.forEach(x=>x._file=file.name);pendingImport.push(...rows);if(!rows.length)warnings.push(`${file.name}: nenhum registro válido.`)}catch(e){warnings.push(`${file.name}: ${e.message}`)}}const dups=detectDuplicates(pendingImport),years=pendingImport.map(x=>x.year).filter(Boolean);$("#corpus-preview").innerHTML=`<div class="grid metrics" style="margin-top:18px"><article class="card metric"><small>Registros válidos</small><div class="value">${pendingImport.length}</div></article><article class="card metric"><small>Possíveis duplicatas</small><div class="value">${dups.length}</div></article><article class="card metric"><small>Ano inicial</small><div class="value">${years.length?Math.min(...years):"—"}</div></article><article class="card metric"><small>Ano final</small><div class="value">${years.length?Math.max(...years):"—"}</div></article></div>${warnings.length?`<div class="notice danger-note">${warnings.map(esc).join("<br>")}</div>`:""}<div class="toolbar"><input id="session-name" placeholder="Nome da sessão" value="Revisão ${new Date().toLocaleDateString("pt-BR")}"><button id="save-import" class="btn btn-primary">Criar sessão</button></div><div class="table-wrap"><table><thead><tr><th>Título</th><th>Ano</th><th>Fonte</th><th>DOI</th><th>Status</th></tr></thead><tbody>${pendingImport.slice(0,100).map((a,i)=>`<tr><td>${esc(a.title)}</td><td>${a.year||"—"}</td><td>${esc(a.source)}</td><td>${esc(a.doi)}</td><td>${dups.some(d=>d.b===i)?`<span class="badge amber">Possível duplicata</span>`:`<span class="badge green">Válido</span>`}</td></tr>`).join("")}</tbody></table></div>`}
function saveImport(){if(!pendingImport.length)return toast("Selecione arquivos válidos.");const name=$("#session-name").value.trim()||"Sessão sem nome",session={id:uid(),owner:state.user.id,name,status:"ready",articleCount:pendingImport.length,duplicateCount:0,deduplicationConfirmed:false,yearRange:"",createdAt:now()};const dups=detectDuplicates(pendingImport),dupIndexes=new Set(dups.map(d=>d.b));pendingImport.forEach((a,i)=>state.articles.push({...a,id:uid(),sessionId:session.id,owner:state.user.id,isDuplicate:dupIndexes.has(i),deduplicationReason:dups.find(d=>d.b===i)?.reason||"",createdAt:now()}));session.duplicateCount=dupIndexes.size;const years=pendingImport.map(x=>x.year).filter(Boolean);session.yearRange=years.length?`${Math.min(...years)}–${Math.max(...years)}`:"—";state.sessions.push(session);save();activity("session_created",`Sessão “${name}” criada com ${pendingImport.length} artigos`,name);pendingImport=[];go(`session/${session.id}`)}

function sessionsPage(){const list=mine(state.sessions);return `${head("Sessões de Análise","Gerencie corpus, duplicatas e indicadores.",`<button class="btn btn-primary" data-go="corpus">Nova sessão</button>`)}${list.length?`<div class="grid">${list.map(s=>`<article class="card"><div class="toolbar" style="justify-content:space-between"><div><h2>${esc(s.name)}</h2><p class="muted">${s.articleCount} artigos · ${s.duplicateCount} duplicatas · ${esc(s.yearRange)}</p></div><button class="btn btn-primary" data-go="session/${s.id}">Abrir</button></div></article>`).join("")}</div>`:empty("Nenhuma sessão","Importe seu primeiro corpus para iniciar.",`<button class="btn btn-primary" data-go="corpus">Importar corpus</button>`)}`}
function sessionDetail(id){const s=state.sessions.find(x=>x.id===id);if(!s)return empty("Sessão não encontrada","O registro pode ter sido removido.");const arts=state.articles.filter(a=>a.sessionId===id);return `${head(esc(s.name),`${arts.length} artigos · ${s.duplicateCount} possíveis duplicatas`,`<div class="actions"><button id="confirm-dedup" class="btn btn-primary">Confirmar deduplicação</button><button id="export-session" class="btn btn-outline">Exportar CSV</button></div>`)}<section class="card"><div class="toolbar"><input id="article-filter" placeholder="Pesquisar título, autor ou DOI"><select id="dup-filter"><option value="all">Todos</option><option value="unique">Não duplicados</option><option value="duplicate">Duplicatas</option></select></div><div id="article-table">${articleTable(arts)}</div></section>`}
function articleTable(arts){return `<div class="table-wrap"><table><thead><tr><th>Título</th><th>Autores</th><th>Ano</th><th>Fonte</th><th>Status</th></tr></thead><tbody>${arts.map(a=>`<tr><td>${esc(a.title)}</td><td>${esc(a.authors||"—")}</td><td>${a.year||"—"}</td><td>${esc(a.source||"—")}</td><td>${a.isDuplicate?`<span class="badge amber">Duplicata</span>`:`<span class="badge green">Mantido</span>`}</td></tr>`).join("")}</tbody></table></div>`}

function statsFor(sessionId){const arts=state.articles.filter(a=>(!sessionId||a.sessionId===sessionId)&&!a.isDuplicate),count=(map,key)=>{if(key)map[key]=(map[key]||0)+1};let years={},journals={},authors={},keywords={},sources={};arts.forEach(a=>{count(years,a.year);count(journals,a.journal);count(sources,a.source);String(a.authors||"").split(/[;,]|\sand\s/i).map(x=>x.trim()).filter(Boolean).forEach(x=>count(authors,x));String(a.keywords||"").split(/[;,]/).map(x=>x.trim().toLowerCase()).filter(Boolean).forEach(x=>count(keywords,x))});const top=(o,n=10)=>Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,n);return {arts,years:top(years,100).sort((a,b)=>+a[0]-+b[0]),journals:top(journals),authors:top(authors),keywords:top(keywords,20),sources:top(sources),citations:arts.reduce((s,a)=>s+(+a.citationCount||0),0)}}
function bars(data){const max=Math.max(1,...data.map(x=>x[1]));return `<div class="bars">${data.map(([l,v])=>`<div class="bar-row"><span title="${esc(l)}">${esc(l||"Não informado")}</span><div class="bar-track"><span style="width:${v/max*100}%"></span></div><b>${v}</b></div>`).join("")||`<p class="muted">Sem dados.</p>`}</div>`}
function resultsPage(){const sessions=mine(state.sessions);const sid=new URLSearchParams(location.hash.split("?")[1]||"").get("session")||sessions[0]?.id;const st=statsFor(sid);return `${head("Resultados","Indicadores calculados sobre artigos não duplicados.",`<button id="print-results" class="btn btn-outline">Imprimir / PDF</button>`)}<section class="card"><div class="field"><label>Sessão</label><select id="result-session">${sessions.map(s=>`<option value="${s.id}" ${s.id===sid?"selected":""}>${esc(s.name)}</option>`).join("")}</select></div></section><section class="grid metrics" style="margin-top:16px"><article class="card metric"><small>Artigos</small><div class="value">${st.arts.length}</div></article><article class="card metric"><small>Citações</small><div class="value">${st.citations}</div></article><article class="card metric"><small>Autores</small><div class="value">${st.authors.length}</div></article><article class="card metric"><small>Palavras-chave</small><div class="value">${st.keywords.length}</div></article></section><section class="grid two-col" style="margin-top:16px"><article class="card"><h2>Publicações por ano</h2>${bars(st.years)}</article><article class="card"><h2>Fontes</h2>${bars(st.sources)}</article><article class="card"><h2>Principais periódicos</h2>${bars(st.journals)}</article><article class="card"><h2>Principais autores</h2>${bars(st.authors)}</article><article class="card" style="grid-column:1/-1"><h2>Palavras-chave</h2>${bars(st.keywords)}</article></section>`}

function screeningPage(){const sessions=mine(state.sessions),ss=mine(state.screeningSessions);return `${head("Triagem de Artigos","Avalie títulos e resumos com critérios explícitos.",`<button id="new-screening" class="btn btn-primary">Nova triagem</button>`)}${ss.length?`<div class="grid">${ss.map(x=>{const ds=state.screeningDecisions.filter(d=>d.screeningSessionId===x.id),done=ds.filter(d=>d.decision!=="pending").length;return `<article class="card"><h2>${esc(x.name)}</h2><p>${done} de ${ds.length} avaliados</p><div class="progress"><span style="width:${ds.length?done/ds.length*100:0}%"></span></div><button class="btn btn-primary" data-go="screen/${x.id}" style="margin-top:12px">Continuar</button></article>`}).join("")}</div>`:empty("Nenhuma triagem","Crie uma triagem a partir de uma sessão deduplicada.")}`}
function createScreening(){const sessions=mine(state.sessions);if(!sessions.length)return toast("Crie uma sessão de análise primeiro.");const opts=sessions.map(s=>`${s.name} (${s.articleCount} artigos)`).join("\n");const name=prompt(`Nome da triagem:\nSessões disponíveis:\n${opts}`,`Triagem ${sessions[0].name}`);if(!name)return;const s=sessions[0],ss={id:uid(),owner:state.user.id,name,analysisSessionId:s.id,status:"in_progress",createdAt:now()};state.screeningSessions.push(ss);state.articles.filter(a=>a.sessionId===s.id&&!a.isDuplicate).forEach(a=>state.screeningDecisions.push({id:uid(),owner:state.user.id,screeningSessionId:ss.id,articleId:a.id,decision:"pending",reason:""}));save();activity("screening_started",`Triagem “${name}” iniciada`,name);go(`screen/${ss.id}`)}
function screenDetail(id){const ss=state.screeningSessions.find(x=>x.id===id),ds=state.screeningDecisions.filter(x=>x.screeningSessionId===id),idx=Math.max(0,ds.findIndex(x=>x.decision==="pending")),d=ds[idx],a=d&&state.articles.find(x=>x.id===d.articleId),done=ds.filter(x=>x.decision!=="pending").length;if(!ss)return empty("Triagem não encontrada","");if(!a)return `${head(esc(ss.name),"Triagem concluída")}<div class="card empty"><h2>Todos os artigos foram avaliados</h2><button class="btn btn-primary" data-go="eligibility">Ir para elegibilidade</button></div>`;return `${head(esc(ss.name),`${done} de ${ds.length} avaliados`)}<div class="progress"><span style="width:${ds.length?done/ds.length*100:0}%"></span></div><section class="grid two-col" style="margin-top:16px"><article class="card article-focus"><span class="badge">${idx+1} de ${ds.length}</span><h2>${esc(a.title)}</h2><p class="muted">${esc(a.authors||"Autores não informados")} · ${a.year||"Ano não informado"}</p><div class="abstract">${esc(a.abstract||"Resumo não disponível. A decisão deve considerar essa limitação.")}</div><div class="field"><label>Motivo ou observação</label><textarea id="decision-reason" placeholder="Obrigatório para exclusão"></textarea></div><div class="decision-actions"><button class="btn btn-primary decision" data-decision="include">Incluir</button><button class="btn btn-danger decision" data-decision="exclude">Excluir</button><button class="btn btn-outline decision" data-decision="pending">Manter pendente</button></div></article><aside class="card"><h3>Critérios de inclusão</h3><ul><li>Espécies animais exóticas invasoras</li><li>Ambientes aquáticos continentais</li><li>Caatinga, semiárido nordestino ou RN</li><li>Período de 2004 a 2025</li><li>Artigo revisado por pares</li></ul><h3>Critérios de exclusão</h3><ul><li>Exclusivamente marinho ou estuarino</li><li>Exclusivamente vegetal</li><li>Sem relação com águas continentais</li><li>Fora da área geográfica</li></ul></aside></section>`}
function decide(screenId,decision){const d=state.screeningDecisions.find(x=>x.screeningSessionId===screenId&&x.decision==="pending");if(!d)return;const reason=$("#decision-reason").value.trim();if(decision==="exclude"&&!reason)return toast("Informe o motivo da exclusão.");d.decision=decision;d.reason=reason;d.screenedAt=now();save();render()}

function eligibilityPage(){const included=mine(state.screeningDecisions).filter(d=>d.decision==="include");included.forEach(d=>{if(!state.eligibilityDecisions.some(e=>e.screeningSessionId===d.screeningSessionId&&e.articleId===d.articleId))state.eligibilityDecisions.push({id:uid(),owner:state.user.id,screeningSessionId:d.screeningSessionId,articleId:d.articleId,decision:"pending",reason:""})});save();const pending=mine(state.eligibilityDecisions).filter(e=>e.decision==="pending"),e=pending[0],a=e&&state.articles.find(x=>x.id===e.articleId);return `${head("Elegibilidade","Decisão final após avaliação do texto completo.")}${a?`<article class="card article-focus"><span class="badge">${pending.length} pendente(s)</span><h2>${esc(a.title)}</h2><p>${esc(a.authors||"")} · ${a.year||"—"}</p>${a.doi?`<p><a href="https://doi.org/${encodeURIComponent(normalizeDOI(a.doi))}" target="_blank" rel="noopener">Abrir DOI</a></p>`:""}<div class="field"><label>Motivo da exclusão</label><textarea id="elig-reason"></textarea></div><div class="decision-actions"><button class="btn btn-primary elig" data-decision="include">Incluir no estudo</button><button class="btn btn-danger elig" data-decision="exclude">Excluir</button><button class="btn btn-outline elig" data-decision="pending">Pendente</button></div></article>`:empty("Nenhum artigo pendente","Inclua artigos na triagem ou conclua os registros restantes.")}`}
function decideEligibility(decision){const e=mine(state.eligibilityDecisions).find(x=>x.decision==="pending");if(!e)return;const reason=$("#elig-reason")?.value.trim()||"";if(decision==="exclude"&&!reason)return toast("Informe o motivo da exclusão.");e.decision=decision;e.reason=reason;e.decidedAt=now();save();render()}

function prismaPage(){const ss=mine(state.screeningSessions)[0];if(!ss)return `${head("Diagrama PRISMA","Fluxo de seleção dos estudos.")}${empty("Sem sessão de triagem","Inicie uma triagem para gerar o diagrama.")}`;const ds=state.screeningDecisions.filter(d=>d.screeningSessionId===ss.id),eds=state.eligibilityDecisions.filter(e=>e.screeningSessionId===ss.id),session=state.sessions.find(s=>s.id===ss.analysisSessionId),identified=(session?.articleCount||ds.length),dups=session?.duplicateCount||0,screened=ds.filter(d=>d.decision!=="pending").length,excluded=ds.filter(d=>d.decision==="exclude").length,inc=ds.filter(d=>d.decision==="include").length,fullEx=eds.filter(e=>e.decision==="exclude").length,finalInc=eds.filter(e=>e.decision==="include").length;return `${head("Diagrama PRISMA 2020",esc(ss.name),`<button class="btn btn-outline" onclick="print()">Imprimir / PDF</button>`)}<div class="prisma"><div class="prisma-box"><b>Registros identificados</b><br>n = ${identified}</div><div class="prisma-arrow">↓</div><div class="prisma-box"><b>Duplicatas removidas</b><br>n = ${dups}</div><div class="prisma-arrow">↓</div><div class="prisma-box"><b>Registros triados</b><br>n = ${screened}</div><div class="prisma-arrow">↓</div><div class="prisma-box"><b>Excluídos por título/resumo</b><br>n = ${excluded}</div><div class="prisma-arrow">↓</div><div class="prisma-box"><b>Avaliados em texto completo</b><br>n = ${inc}</div><div class="prisma-arrow">↓</div><div class="prisma-box"><b>Excluídos após texto completo</b><br>n = ${fullEx}</div><div class="prisma-arrow">↓</div><div class="prisma-box"><b>Estudos incluídos</b><br>n = ${finalInc}</div></div>`}

function mapPage(){return `${head("Mapa de Espécies","Consulte ocorrências georreferenciadas na API pública do GBIF.")}<section class="grid two-col"><form id="gbif-form" class="card"><div class="field"><label>Nome científico</label><input name="species" placeholder="Ex.: Oreochromis niloticus" required></div><div class="grid two-col"><div class="field"><label>Ano inicial</label><input name="y1" type="number" value="2004"></div><div class="field"><label>Ano final</label><input name="y2" type="number" value="2025"></div></div><button class="btn btn-primary">Consultar GBIF</button><p class="muted"><small>A consulta exige internet. Registros sem coordenadas são omitidos.</small></p></form><article class="card"><h2>Qualidade dos dados</h2><p class="muted">A presença no GBIF não confirma estabelecimento ou invasividade. Verifique identificação, coordenadas, data e fonte antes do uso científico.</p></article></section><section id="gbif-results" style="margin-top:16px"></section>`}
async function gbifSearch(form){const f=new FormData(form),name=f.get("species"),year=`${f.get("y1")},${f.get("y2")}`,box=$("#gbif-results");box.innerHTML=`<div class="card">Consultando GBIF…</div>`;try{const species=await fetch(`https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}`).then(r=>r.json());if(!species.usageKey)throw new Error("Táxon não encontrado");const data=await fetch(`https://api.gbif.org/v1/occurrence/search?taxon_key=${species.usageKey}&country=BR&state_province=Rio%20Grande%20do%20Norte&year=${year}&has_coordinate=true&limit=100`).then(r=>r.json());const rows=data.results.map(r=>({id:uid(),owner:state.user.id,key:r.key,species:r.scientificName||name,lat:r.decimalLatitude,lon:r.decimalLongitude,date:r.eventDate||r.year,locality:r.locality||r.stateProvince||"RN",dataset:r.datasetTitle||"GBIF"}));state.occurrences.push(...rows.filter(r=>!state.occurrences.some(x=>x.key===r.key)));save();box.innerHTML=`<article class="card"><h2><span class="species">${esc(species.scientificName||name)}</span></h2><p>${data.count} ocorrência(s) no total; exibindo ${rows.length} registros coordenados.</p><div class="table-wrap map-results"><table><thead><tr><th>Localidade</th><th>Data</th><th>Coordenadas</th><th>Fonte</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.locality)}</td><td>${esc(r.date||"—")}</td><td><a target="_blank" rel="noopener" href="https://www.openstreetmap.org/?mlat=${r.lat}&mlon=${r.lon}">${r.lat.toFixed(4)}, ${r.lon.toFixed(4)}</a></td><td><a target="_blank" rel="noopener" href="https://www.gbif.org/occurrence/${r.key}">${esc(r.dataset)}</a></td></tr>`).join("")}</tbody></table></div></article>`}catch(e){box.innerHTML=`<div class="notice danger-note">Não foi possível consultar o GBIF: ${esc(e.message)}.</div>`}}

function vosPage(){const sessions=mine(state.sessions);return `${head("VOSviewer","Exporte redes de coautoria e coocorrência de palavras-chave.")}<section class="card"><div class="field"><label>Sessão</label><select id="vos-session">${sessions.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></div><div class="actions"><button class="btn btn-primary vos-export" data-kind="authors">Exportar coautoria</button><button class="btn btn-outline vos-export" data-kind="keywords">Exportar palavras-chave</button></div><div class="notice" style="margin-top:16px">No VOSviewer, escolha “Create a map based on network data” e selecione os arquivos exportados.</div></section>`}
function exportVos(kind){const sid=$("#vos-session").value,arts=state.articles.filter(a=>a.sessionId===sid&&!a.isDuplicate),field=kind==="authors"?"authors":"keywords",sep=/[;,]|\sand\s/i,weights={};arts.forEach(a=>String(a[field]||"").split(sep).map(x=>x.trim()).filter(Boolean).forEach(x=>weights[x]=(weights[x]||0)+1));const txt="id\tlabel\tweight\n"+Object.keys(weights).map((x,i)=>`${i+1}\t${x}\t${weights[x]}`).join("\n");download(`vosviewer-${kind}.txt`,txt)}
function adminPage(){return `${head("Administração","Backup local e informações da instalação.")}<section class="grid two-col"><article class="card"><h2>Backup dos dados</h2><p class="muted">Exporte periodicamente uma cópia. Os dados desta versão ficam somente no navegador.</p><div class="actions"><button id="backup-export" class="btn btn-primary">Exportar backup</button><label class="btn btn-outline">Importar backup<input id="backup-import" type="file" accept="application/json" hidden></label></div></article><article class="card"><h2>Instalação PWA</h2><p class="muted">Use a opção “Instalar aplicativo” do navegador. Após o primeiro carregamento, a plataforma funciona offline, exceto o GBIF.</p><button id="install-app" class="btn btn-primary">Instalar EcoMétrica</button></article><article class="card"><h2>Conta atual</h2><p><b>${esc(state.user.name)}</b><br>${esc(state.user.email)}<br>${esc(state.user.institution||"")}</p><span class="badge green">${esc(state.user.role)}</span></article><article class="card"><h2>Armazenamento</h2><p>${state.sessions.length} sessões · ${state.articles.length} artigos · ${state.activities.length} atividades</p><button id="clear-demo" class="btn btn-danger">Limpar dados científicos</button></article></section>`}

function page(){if(!authReady)return `<div class="auth-wrap"><div class="card auth-card"><div class="brand"><img src="icons/icon.svg" alt=""><span>EcoMétrica</span></div><p class="muted">Conectando com segurança…</p></div></div>`;const r=route(),[base,id]=r.split("/");if(!state.user)return r==="login"?authPage("login"):r==="register"?authPage("register"):landing();const pages={dashboard:dashboard,search:searchPage,map:mapPage,corpus:corpusPage,sessions:sessionsPage,screening:screeningPage,eligibility:eligibilityPage,prisma:prismaPage,results:resultsPage,vosviewer:vosPage,admin:adminPage};return shell(base==="session"?sessionDetail(id):base==="screen"?screenDetail(id):(pages[base]||dashboard)())}
function render(){$("#app").innerHTML=page();bind()}

function bind(){
  $$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
  $("#menu-toggle")?.addEventListener("click",()=>$("#sidebar").classList.toggle("open"));
  $("#logout")?.addEventListener("click",async()=>{await supabaseClient.auth.signOut();state.user=null;go("home");render()});
  $("#google-login")?.addEventListener("click",async()=>{const button=$("#google-login");button.disabled=true;button.textContent="Abrindo Google…";const redirectTo="https://egbertomesquita-cmd.github.io/ecometrica-pwa/?auth=google";const {error}=await supabaseClient.auth.signInWithOAuth({provider:"google",options:{redirectTo}});if(error){toast(`Não foi possível abrir o Google: ${error.message}`);button.disabled=false;button.innerHTML='<span class="google-mark" aria-hidden="true">G</span>Continuar com Google'}});
  $("#auth-form")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button[type="submit"]'),f=new FormData(form),email=String(f.get("email")).toLowerCase(),password=String(f.get("password"));button.disabled=true;button.textContent="Aguarde…";try{if(route()==="register"){const {data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{full_name:f.get("name"),institution:f.get("institution")}}});if(error)throw error;if(!data.session){toast("Cadastro criado. Confirme o e-mail antes de entrar.");setTimeout(()=>go("login"),1200);return}await hydrateUser(data.user)}else{const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error;await hydrateUser(data.user)}go("dashboard");render()}catch(error){toast(authMessage(error.message));button.disabled=false;button.textContent=route()==="register"?"Criar conta":"Entrar"}});
  $("#search-form")?.addEventListener("submit",e=>{e.preventDefault();renderStrategies(e.currentTarget)});
  $("#strategies")?.addEventListener("click",e=>{if(e.target.classList.contains("copy-strategy")){navigator.clipboard.writeText(e.target.closest(".card").querySelector(".strategy").innerText);toast("Estratégia copiada.")}if(e.target.id==="export-strategies"){const t=$$(".strategy").map(x=>x.innerText).join("\n\n");download("estrategias-ecometrica.txt",t)}});
  $("#corpus-files")?.addEventListener("change",e=>handleFiles(e.target.files));
  $("#corpus-preview")?.addEventListener("click",e=>{if(e.target.id==="save-import")saveImport()});
  $("#confirm-dedup")?.addEventListener("click",()=>{const id=route().split("/")[1],s=state.sessions.find(x=>x.id===id);s.deduplicationConfirmed=true;save();activity("dedup_confirmed",`Deduplicação confirmada em “${s.name}”`,s.name);toast("Deduplicação confirmada.")});
  $("#export-session")?.addEventListener("click",()=>{const id=route().split("/")[1],arts=state.articles.filter(a=>a.sessionId===id),keys=["title","authors","journal","year","doi","keywords","source","isDuplicate"];download("sessao-ecometrica.csv",keys.join(",")+"\n"+arts.map(a=>keys.map(k=>`"${String(a[k]??"").replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv")});
  $("#article-filter")?.addEventListener("input",filterArticles);$("#dup-filter")?.addEventListener("change",filterArticles);
  $("#result-session")?.addEventListener("change",e=>{location.hash=`#/results?session=${e.target.value}`});$("#print-results")?.addEventListener("click",()=>print());
  $("#new-screening")?.addEventListener("click",createScreening);$$('.decision').forEach(b=>b.onclick=()=>decide(route().split("/")[1],b.dataset.decision));$$('.elig').forEach(b=>b.onclick=()=>decideEligibility(b.dataset.decision));
  $("#gbif-form")?.addEventListener("submit",e=>{e.preventDefault();gbifSearch(e.currentTarget)});$$('.vos-export').forEach(b=>b.onclick=()=>exportVos(b.dataset.kind));
  $("#backup-export")?.addEventListener("click",()=>download(`ecometrica-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2),"application/json"));
  $("#backup-import")?.addEventListener("change",async e=>{try{state=JSON.parse(await e.target.files[0].text());save();toast("Backup restaurado.");render()}catch{toast("Backup inválido.")}});
  $("#clear-demo")?.addEventListener("click",()=>{if(confirm("Remover sessões, artigos, decisões e atividades deste dispositivo?")){state={...state,sessions:[],articles:[],screeningSessions:[],screeningDecisions:[],eligibilityDecisions:[],activities:[],occurrences:[]};save();render()}});
  $("#install-app")?.addEventListener("click",async()=>{if(window.installPrompt){window.installPrompt.prompt();await window.installPrompt.userChoice;window.installPrompt=null}else toast("Use o menu do navegador para instalar.")});
}
function filterArticles(){const id=route().split("/")[1],q=norm($("#article-filter").value),d=$("#dup-filter").value;const arts=state.articles.filter(a=>a.sessionId===id&&(!q||norm(`${a.title} ${a.authors} ${a.doi}`).includes(q))&&(d==="all"||(d==="duplicate")===a.isDuplicate));$("#article-table").innerHTML=articleTable(arts)}

window.addEventListener("hashchange",render);window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();window.installPrompt=e});
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
function authMessage(message=""){if(/invalid login credentials/i.test(message))return "E-mail ou senha inválidos.";if(/user already registered/i.test(message))return "E-mail já cadastrado.";if(/password/i.test(message))return "A senha deve ter pelo menos 8 caracteres.";return `Não foi possível autenticar: ${message}`}
async function hydrateUser(user){if(!user){state.user=null;return}const {data:profile}=await supabaseClient.from("profiles").select("email, full_name, institution, role").eq("id",user.id).single();state.user={id:user.id,email:user.email,name:profile?.full_name||user.user_metadata?.full_name||user.email.split("@")[0],institution:profile?.institution||user.user_metadata?.institution||"",role:profile?.role||"researcher"}}
function finishOAuth(){if(new URLSearchParams(location.search).get("auth")!=="google")return false;history.replaceState(null,"",`${location.pathname}#/dashboard`);return true}
async function initAuth(){try{const {data:{session}}=await supabaseClient.auth.getSession();await hydrateUser(session?.user||null);if(session?.user)finishOAuth()}catch(error){console.error("Falha ao iniciar autenticação",error)}finally{authReady=true;render()}}
supabaseClient.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_IN"&&session?.user)setTimeout(async()=>{await hydrateUser(session.user);authReady=true;finishOAuth();if(["home","login","register"].includes(route()))go("dashboard");render()},0);if(authReady&&event==="SIGNED_OUT"){state.user=null;render()}});
render();initAuth();
