create schema if not exists private;

create table if not exists public.audit_history (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text not null default '',
  actor_name text not null default '',
  entity_type text not null,
  entity_id text not null,
  action text not null check (action in ('insert', 'update', 'delete')),
  version integer not null check (version > 0),
  changed_fields text[] not null default '{}',
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now(),
  unique (owner_id, entity_type, entity_id, version)
);

create index if not exists audit_history_owner_created_idx
  on public.audit_history (owner_id, created_at desc);

create index if not exists audit_history_entity_version_idx
  on public.audit_history (owner_id, entity_type, entity_id, version desc);

alter table public.audit_history enable row level security;

drop policy if exists "audit_history_select_own" on public.audit_history;
create policy "audit_history_select_own"
on public.audit_history for select to authenticated
using ((select auth.uid()) = owner_id);

revoke all on public.audit_history from anon;
revoke insert, update, delete on public.audit_history from authenticated;
grant select on public.audit_history to authenticated;

create or replace function private.capture_audit_history()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  before_row jsonb := case when tg_op = 'INSERT' then null else to_jsonb(old) end;
  after_row jsonb := case when tg_op = 'DELETE' then null else to_jsonb(new) end;
  row_owner uuid;
  row_id text;
  entity_name text;
  fields text[];
  next_version integer;
  current_actor uuid := auth.uid();
  current_email text := coalesce(auth.jwt() ->> 'email', '');
  current_name text := '';
begin
  if tg_table_name = 'scientific_records' and tg_op = 'UPDATE'
     and old.payload is not distinct from new.payload then
    return null;
  end if;

  row_owner := coalesce((after_row ->> 'owner_id')::uuid, (before_row ->> 'owner_id')::uuid, current_actor);
  if row_owner is null then
    return null;
  end if;

  entity_name := case when tg_table_name = 'scientific_records'
    then coalesce(after_row ->> 'record_type', before_row ->> 'record_type', tg_table_name)
    else tg_table_name
  end;
  row_id := case when tg_table_name = 'scientific_records'
    then coalesce(after_row ->> 'record_id', before_row ->> 'record_id')
    else coalesce(after_row ->> 'id', before_row ->> 'id')
  end;

  select coalesce(array_agg(key order by key), '{}') into fields
  from (
    select key from jsonb_object_keys(coalesce(before_row, '{}'::jsonb)) as key
    union
    select key from jsonb_object_keys(coalesce(after_row, '{}'::jsonb)) as key
  ) keys
  where (before_row -> key) is distinct from (after_row -> key)
    and key not in ('updated_at', 'created_at');

  select coalesce(full_name, '') into current_name
  from public.profiles
  where id = current_actor;
  current_name := coalesce(current_name, '');

  perform pg_advisory_xact_lock(hashtextextended(row_owner::text || ':' || entity_name || ':' || row_id, 0));
  select coalesce(max(version), 0) + 1 into next_version
  from public.audit_history
  where owner_id = row_owner and entity_type = entity_name and entity_id = row_id;

  insert into public.audit_history (
    owner_id, actor_id, actor_email, actor_name, entity_type, entity_id,
    action, version, changed_fields, old_data, new_data
  ) values (
    row_owner, current_actor, current_email, current_name, entity_name, row_id,
    lower(tg_op), next_version, fields, before_row, after_row
  );

  return null;
end;
$$;

revoke all on function private.capture_audit_history() from public, anon, authenticated;

drop trigger if exists audit_research_projects on public.research_projects;
create trigger audit_research_projects
after insert or update or delete on public.research_projects
for each row execute function private.capture_audit_history();

drop trigger if exists audit_search_strategies on public.search_strategies;
create trigger audit_search_strategies
after insert or update or delete on public.search_strategies
for each row execute function private.capture_audit_history();

drop trigger if exists audit_search_executions on public.search_executions;
create trigger audit_search_executions
after insert or update or delete on public.search_executions
for each row execute function private.capture_audit_history();

drop trigger if exists audit_scientific_records on public.scientific_records;
create trigger audit_scientific_records
after insert or delete or update on public.scientific_records
for each row
execute function private.capture_audit_history();
